name: Build, Push, and Deploy to ECS

on:
  push:
    branches:
      - main
      - fargate
    paths:
      - "path-based/**"
      - ".github/workflows/**" # Triggers if you update this pipeline file
  workflow_dispatch: # Allows you to trigger deployments/secret rotations manually via the GitHub UI

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: lirw-dev
  ECS_SERVICE: lirw-service-dev
  ECS_CLUSTER: ecs-cluster-dev
  ECS_TASK_DEFINITION: task-definition.json
  CONTAINER_NAME: lirw
  PROJECT_NAME: ECS-LIRW-ALB # MUST match the var.project_name used in your Terraform
  DOMAIN_NAME: devsandbox.space

# REQUIRED FOR OIDC
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: "authors"
            port: 3300
            env: "[]"
          - service: "books"
            port: 3400
            env: "[]"
          - service: "dashboard"
            port: 3200
            env: '[{"name": "BOOKS_SERVICE_URL", "value": "https://${{ vars.DOMAIN_NAME }}/books"}, {"name": "AUTHORS_SERVICE_URL", "value": "https://${{ vars.DOMAIN_NAME }}/authors"}]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/GitHubActions-ECS-DeployRole
          aws-region: ${{ env.AWS_REGION }}

      # ---------------------------------------------------------
      # BUILD & DEPLOY
      # ---------------------------------------------------------
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          REPO_NAME: ${{ matrix.service }}-repo-${{vars.ENV_VAR}}
        run: |
          cd path-based
          # Assumes Dockerfiles are in folders named 'authors', 'books', 'dashboard'
          docker build -t $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG ./${{ matrix.service }}
          docker push $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

      #   - name: Inject Variables into JSON
      #     env:
      #       SERVICE_NAME: ${{ matrix.service }}
      #       APP_PORT: ${{ matrix.port }}
      #       ENVIRONMENT_VARS: ${{ matrix.env }}
      #       ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}
      #       APP_CPU: ${{ vars.APP_CPU }}
      #       APP_MEMORY: ${{ vars.APP_MEMORY }}
      #     run: |
      #       # envsubst fills in the ports and the JSON array for environment variables
      #       envsubst < ${{ env.ECS_TASK_DEFINITION }}.template > ${{ env.ECS_TASK_DEFINITION }}

      - name: Download current ECS task definition
        run: |
          # Fetches the active task definition from AWS and saves it to a temporary JSON file
          aws ecs describe-task-definition \
            --task-definition lirw-task-${{ matrix.service }} \
            --query taskDefinition > ${{ env.ECS_TASK_DEFINITION }}

      - name: Fill in the new image ID
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: lirw-${{ matrix.service }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ matrix.service }}-service-${{ vars.ENV_VAR }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
